name: hpack
version: 0.34.2
synopsis: A modern format for Haskell packages
description: See README at <https://github.com/sol/hpack#readme>
maintainer: Simon Hengel <sol@typeful.net>
github: sol/hpack
category: Development

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 5
  - parsec
  - split
  - casing
  - extra

executable:
  main: Main.hs
  source-dirs: .
  dependencies:
    - hpack


